/* ---------------------------------------------------------
   Sample data — 5 Green Volley + 2 Beach Volley, all in FVG
--------------------------------------------------------- */
export const INITIAL_TOURNAMENTS = [
  {
    id: 't1',
    nome: 'Smash in the Grass',
    disciplina: 'Green Volley',
    formati: ['3x3'],
    modalita: 'Misto, minimo 2 donne in campo',
    data: '2026-08-15',
    dataFine: '',
    ora: '09:00',
    luogo: 'Parco del Cormor',
    comune: 'Udine',
    provincia: 'UD',
    costo: '15',
    iscrizioniEntro: '2026-08-10',
    organizzatore: 'ASD Udine Volley',
    descrizioneOrganizzatore: 'Torneo giunto alla 3ª edizione. Per iscrizioni last-minute o info scrivete a Marco, 338 123 4567.',
    instagram: 'https://instagram.com/udinevolley',
    facebook: 'https://facebook.com/udinevolley',
    locandina: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT410OQY276wgF3Ojd9jIZ_tBBrro03UBHgmWEX5jnoJBetFw54M2C_6ykY&s=10',
  },
  {
    id: 't2',
    nome: 'Green Volley Cormor',
    disciplina: 'Green Volley',
    formati: ['4x4'],
    modalita: 'Misto, minimo 2 donne in campo',
    data: '2026-08-16',
    dataFine: '',
    ora: '15:30',
    luogo: 'Campo Sportivo Comunale',
    comune: 'Codroipo',
    provincia: 'UD',
    costo: '€60',
    iscrizioniEntro: '2026-08-12',
    organizzatore: 'Codroipo Sport Events',
    descrizioneOrganizzatore: '',
    instagram: 'https://instagram.com/codroiposport',
    facebook: '',
    locandina: 'https://www.volleycormor.it/wp-content/uploads/2026/06/locandina.webp',
  },
  {
    id: 't3',
    nome: 'Green Volley Teor',
    disciplina: 'Green Volley',
    formati: ['3x3'],
    modalita: 'Misto, minimo 1 donna in campo',
    data: '2026-08-22',
    dataFine: '',
    ora: '18:00',
    luogo: 'Parco Basaglia',
    comune: 'Gorizia',
    provincia: 'GO',
    costo: '€12 a giocatore',
    iscrizioniEntro: '2026-08-18',
    organizzatore: 'Gorizia Volley Club',
    descrizioneOrganizzatore: '',
    instagram: 'https://instagram.com/goriziavolley',
    facebook: '',
    locandina: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSW2vSQzJjkhQo9hquu76ikccdmgS2t9mYTb-IHu8U3l4rYAlbr2o9YtN4&s=10',
  },
  {
    id: 't4',
    nome: 'Lignano Beach Marathon',
    disciplina: 'Beach Volley',
    formati: ['2x2', '3x3', '4x4'],
    modalita: 'Open, senza vincoli di genere — iscriviti a una o più categorie',
    data: '2026-08-29',
    dataFine: '2026-08-30',
    ora: '09:00',
    luogo: 'Spiaggia Lignano Pineta',
    comune: 'Lignano Sabbiadoro',
    provincia: 'UD',
    costo: '€25 a coppia (2x2), €15 a giocatore (3x3/4x4)',
    iscrizioniEntro: '2026-08-24',
    organizzatore: 'Lignano Beach Tour',
    descrizioneOrganizzatore: 'Due giorni no-stop sulla sabbia: sabato 2x2 e 3x3, domenica 4x4. Premi per il vincitore assoluto. Info: Sara, 347 987 6543.',
    instagram: 'https://instagram.com/lignanobeachtour',
    facebook: 'https://facebook.com/lignanobeachtour',
    locandina: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT410OQY276wgF3Ojd9jIZ_tBBrro03UBHgmWEX5jnoJBetFw54M2C_6ykY&s=10',
  },
  {
    id: 't5',
    nome: 'Grado Sand Battle',
    disciplina: 'Beach Volley',
    formati: ['4x4'],
    modalita: 'Misto, minimo 2 donne in campo',
    data: '2026-09-05',
    dataFine: '',
    ora: '16:00',
    luogo: 'Spiaggia Grado Pineta',
    comune: 'Grado',
    provincia: 'GO',
    costo: '€70 a squadra',
    iscrizioniEntro: '2026-08-30',
    organizzatore: 'Grado Beach Events',
    descrizioneOrganizzatore: '',
    instagram: 'https://instagram.com/gradobeachevents',
    facebook: '',
    locandina: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT410OQY276wgF3Ojd9jIZ_tBBrro03UBHgmWEX5jnoJBetFw54M2C_6ykY&s=10',
  },
  {
    id: 't6',
    nome: 'Erba Alta Fest',
    disciplina: 'Green Volley',
    formati: ['2x2'],
    modalita: 'Open, senza vincoli di genere',
    data: '2026-09-06',
    dataFine: '',
    ora: '09:30',
    luogo: 'Parco San Valentino',
    comune: 'Pordenone',
    provincia: 'PN',
    costo: '€20 a coppia',
    iscrizioniEntro: '2026-09-01',
    organizzatore: 'ASD Pordenone Volley',
    descrizioneOrganizzatore: '',
    instagram: 'https://instagram.com/pordenonevolley',
    facebook: 'https://facebook.com/pordenonevolley',
    locandina: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT410OQY276wgF3Ojd9jIZ_tBBrro03UBHgmWEX5jnoJBetFw54M2C_6ykY&s=10',
  },
  {
    id: 't7',
    nome: 'Settembre in Movimento',
    disciplina: 'Green Volley',
    formati: ['6x6'],
    modalita: 'Misto, minimo 2 donne in campo',
    data: '2026-09-12',
    dataFine: '',
    ora: '10:00',
    luogo: 'Bosco Bovedo',
    comune: 'Trieste',
    provincia: 'TS',
    costo: '€90 a squadra',
    iscrizioniEntro: '2026-09-05',
    organizzatore: 'Trieste Volley Community',
    descrizioneOrganizzatore: '',
    instagram: 'https://instagram.com/triestevolley',
    facebook: '',
    locandina: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT410OQY276wgF3Ojd9jIZ_tBBrro03UBHgmWEX5jnoJBetFw54M2C_6ykY&s=10',
  },
];

export const INITIAL_ANNUNCI = [
  {
    id: 'b1',
    tipo: 'cerca_giocatore',
    testo:
      'ASD Udine Volley cerca 2 giocatori per completare il roster del Green Volley di Ferragosto (15/8, Parco del Cormor). Livello amatoriale, si gioca per divertirsi. Scrivete su IG @asdudinevolley.',
    data: '2026-08-04',
    rotazione: -1.5,
  },
  {
    id: 'b2',
    tipo: 'cerca_squadra',
    testo:
      'Ciao! Sono libera per tutto agosto, gioco centrale/opposto da 4 anni, livello amatoriale ma con tanta voglia di giocare 😄 Zona Udine/Pordenone, ma mi muovo. Scrivetemi su IG @giulia.volley',
    data: '2026-08-03',
    rotazione: 2,
  },
  {
    id: 'b3',
    tipo: 'cerca_giocatore',
    testo: 'Siamo 2 ragazzi e 1 ragazza e cerchiamo gente per il torneo di Majano del 12-13 settembre: 2 ragazze e 1 ragazzo, oppure 2 ragazzi e 3 ragazze. Livello tranquillo, si punta a divertirsi. Contattatemi su Facebook: @MatteoRossi',
    data: '2026-08-02',
    rotazione: -1,
  }
];
